### ISSUE TITLE
你好，圆环进度条可以逆时针动画吗？

### ISSUE THREAD

**Issue by Gala-1024** [huhaixiang/vue-calendar#1]
你好，圆环进度条可以逆时针动画吗？
比如从100到30

**Comment by huhaixiang** [comment]
暂时还没有，有空时候可以加一下

**Comment by Gala-1024** [comment]
可以用ctx.arc这个方法的最后一个参数传true实现逆向画图，但是进度条的动画公式用原来的好像不对。会有问题，静态逆向画图没问题
